### ISSUE TITLE
m.expect not recognized as jasmine expectation (SPEC HAS NO EXPECTATIONS)

### ISSUE THREAD

**Issue by MartinNuc** [cartant/rxjs-marbles#51] opened 2018-11-10 13:26 UTC
In my Angular7 I made very simple test:

```
it('should see expectations', marbles(m => {
  const source: Observable<Message> = m.hot('^a--b--c');
  m.expect(source).toBeObservable('-a--b--c');
}));
```

But I get in console error:

```
ERROR: 'Spec 'MyService should see expectations' has no expectations.
```

And my test is prefixed with `SPEC HAS NO EXPECTATIONS`.

Adding `expect(true).toBe(true);` helps but I guess jasmine should recognize `m.expect` as expectation, right?

I posted also stackoverflow question: https://stackoverflow.com/questions/53239173/rxjs-marbles-testing-has-no-expectations but I feel here I have better chance to understand the problem.

Also I looked on tests in this repository and there is no such message and I couldn't find any settings related to this problem. Thank you for help.

Dependencies:
```
"rxjs-marbles": "4.3.2"
"jasmine-core": "3.2.1"
```

**Comment by cartant** [comment] 2018-11-10 20:58
I cannot reproduce the problem using Jasmine 3.3.0 with the following spec:

```ts
import { marbles } from "rxjs-marbles/jasmine";

it("should see expectations", marbles(m => {
    const source = m.hot("^a--b--c");
    m.expect(source).toBeObservable("-a--b--c");
}));
```
and this command (from within an npm script):

```
jasmine ./fixtures/jasmine/*-spec.js
```

It's not clear whether the error you've mentioned is a Jasmine error or an error from some other tool - a linter, perhaps?

The expectation is not a Jasmine expectation because it defaults to using its own deep-equal comparison and throwing its own error - which has a messages that's easier to read than the messages from some test frameworks (with Jest being the exception).

You could try the following to see if it solves your problem:

```ts
import { configure } from "rxjs-marbles/jasmine";
const { marbles } = configure({
    assertDeepEqual: (a, e) => expect(a).toEqual(e)
});
```

**Comment by cartant** [comment] 2018-11-11 01:06
FWIW, I've changed the implementation behind the `rxjs-marbles/jasmine` import location to use Jasmine's assertions/expectations. However, npm isn't letting me publish a new version of the package.

**Comment by cartant** [comment] 2018-11-11 08:29
If `configure` doesn't make a difference, I cannot see how the new version won't either. It just calls `configure` internally.

For me to be able to help, you will need to provide me with all of the steps necessary to reproduce the problem.

**Comment by MartinNuc** [comment] 2018-11-11 08:32
I will try to create a bare repo for reproduction

**Comment by cartant** [comment] 2018-11-11 08:34
Make sure you use the latest version. I just deleted a comment regarding `configure`. The snippet above should have included `assert`, too, [as done here](https://github.com/cartant/rxjs-marbles/blob/v4.3.3/source/jasmine/index.ts#L34-L38) in the latest version.

**Comment by MartinNuc** [comment] 2018-11-11 08:37
Actually in bare repo it works well. I will try to add library used in our project one by one and lets see where this message comes from.

**Comment by MartinNuc** [comment] 2018-11-11 08:55
Alright I was able to reproduce it: https://github.com/MartinNuc/rxjs-marbles-no-expectations

I am going to play with it now to find what exactly is causing the issue.

**Comment by cartant** [comment] 2018-11-11 09:00
I wouldn't surprised if it turns out to be related to `zone.js`.

**Comment by MartinNuc** [comment] 2018-11-11 09:57
This works:

```
"karma": "~3.0.1",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "0.2.2",
"jasmine-core": "~2.99.1",
"jasmine-spec-reporter": "~4.2.1",
```

This does not:

```
"jasmine-core": "3.3.0",
"jasmine-spec-reporter": "4.2.1",
"karma": "3.1.1",
"karma-jasmine": "1.1.2",
"karma-jasmine-html-reporter": "1.4.0"
```

That information is added by [karma-jasmine-html-reporter](https://github.com/dfederm/karma-jasmine-html-reporter/blob/baa99b59a811b171b621bf19d2349d38551c51b6/src/lib/html.jasmine.reporter.js#L142). Looks like arrays in `noExpectations()` comes from [addExpectationResult](https://github.com/jasmine/jasmine/blob/b3ccd4312cc96671d0d3d0d951a87b82dc15d7ad/lib/jasmine-core/jasmine.js#L586). Not sure what is supposed to call that method.

**Comment by cartant** [comment] 2018-11-11 12:07
This should be fixed in 4.3.4. I messed up the overriding of the default configuration. Importing from `rxjs-marbles/jasmine` should now see Jasmine's `expect` used in the internal assertions. If the latest version doesn't solve the problem, there's nothing that I can do about it and you'll have to report the error against the package you've mentioned above - as the latest version *definitely* calls Jasmine's `expect` function.

**Comment by MartinNuc** [comment] 2018-11-11 21:32
Thank you very much. It works! Just one more thing - it requires `"jasmine-core": "3.3.0",`

With `"jasmine-core": "3.2.1",` it gives: 

```
        TypeError: expect(...).withContext is not a function
            at <Jasmine>
            at assert (http://localhost:9876/node_modules/rxjs-marbles/esm5/jasmine/index.js?:21:85)
            at observableMatcher (http://localhost:9876/node_modules/rxjs-marbles/esm5/matcher.js?:39:1)
            at TestScheduler.assertDeepEqual (http://localhost:9876/node_modules/rxjs-marbles/esm5/marbles.js?:36:95)
            at http://localhost:9876/node_modules/rxjs/_esm5/internal/testing/TestScheduler.js?:122:1
...
```

I guess you cannot force that version through `package.json` since this library is not only for jasmine, right?

**Comment by cartant** [comment] 2018-11-11 21:38
That's a bit of a pain.

I need the context to give a sensible message.

I'll have to check for it at runtime and that also means you'll still get the no-expectation error if not using 3.3.0 or whatever.

**Comment by cartant** [comment] 2018-11-11 22:00
Let's try again with 4.3.5. But you will still get the no-expectations error unless you use Jasmine 3.3.0.

**Comment by MartinNuc** [comment] 2018-11-11 22:13
Good. Now it gives me that `SPEC HAS NO EXPECTATIONS` with older version. Once I install `"jasmine-core": "3.3.0"` it works well.

There is a chance that one with `"jasmine-core": "3.2.1",` will google this thread :-) So I guess we can close it now 👍 

Thank you for very quick response. This project is great and it really helps us a lot to test observables. You do great job! 🙇‍♂️

**Closed as completed** 2018-11-11 22:24 UTC

**Comment by Insulince** [comment] 2019-01-14 15:14
FYI, to hopefully save some time for someone else in the future, the problem was resolved for me by following @cartant's suggestion of importing `rxjs-marbles/jasmine` (instead of just `rxjs-marbles`) fixed the problem for me.

So:
`import {marbles} from "rxjs-marbles";`
does not fix the expectation issue, while:
`import {marbles} from "rxjs-marbles/jasmine";`
does.

This is especially annoying because my IDE likes to import the incorrect version by default, so remain vigilant about this!

Adding relevant packages from `pacakge.json` for the record:
```
"npm": "^6.4.0", 
"rxjs": "^6.3.3",
"@types/jasmine": "^2.8.8",
"istanbul-instrumenter-loader": "^3.0.1",
"jasmine-core": "^3.3.0",
"jasmine-spec-reporter": "^4.2.1",
"karma": "^3.0.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage": "^1.1.2",
"karma-coverage-istanbul-reporter": "^2.0.1",
"karma-jasmine": "^1.1.2",
"karma-jasmine-html-reporter": "^1.4.0",
"karma-spec-reporter": "0.0.32",
"rxjs-marbles": "^5.0.0",
"tslint": "~5.11.0",
"typescript": "3.1.3"
```

**Comment by vkiperman** [comment] 2021-11-05 11:54
This was so helpful!!!
Thank you
